// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BaseDigimon struct {
	ID          int32  `json:"id"`
	Species     string `json:"species"`
	BaseHealth  int32  `json:"base_health"`
	BaseAttack  int32  `json:"base_attack"`
	BaseDefense int32  `json:"base_defense"`
	BaseMana    int32  `json:"base_mana"`
	BaseSpeed   int32  `json:"base_speed"`
	Form        string `json:"form"`
	Attribute   string `json:"attribute"`
	Family      string `json:"family"`
	Element     string `json:"element"`
}

type Chapter struct {
	ID            int32       `json:"id"`
	ChapterName   string      `json:"chapter_name"`
	ChapterNumber string      `json:"chapter_number"`
	Description   pgtype.Text `json:"description"`
	IsUnlocked    pgtype.Bool `json:"is_unlocked"`
}

type Episode struct {
	ID            int32       `json:"id"`
	ChapterID     pgtype.Int4 `json:"chapter_id"`
	EpisodeNumber int32       `json:"episode_number"`
	EpisodeName   string      `json:"episode_name"`
}

type Stage struct {
	ID            int32       `json:"id"`
	ChapterID     pgtype.Int4 `json:"chapter_id"`
	EpisodeID     pgtype.Int4 `json:"episode_id"`
	StageNumber   int32       `json:"stage_number"`
	StageName     string      `json:"stage_name"`
	Description   pgtype.Text `json:"description"`
	DefeatStageID pgtype.Int4 `json:"defeat_stage_id"`
	TamerLevel    pgtype.Int4 `json:"tamer_level"`
	DropBits      pgtype.Int4 `json:"drop_bits"`
	DropExp       pgtype.Int4 `json:"drop_exp"`
	DropSexp      pgtype.Int4 `json:"drop_sexp"`
	MaxWaves      pgtype.Int4 `json:"max_waves"`
	StageType     pgtype.Text `json:"stage_type"`
}

type StageWafe struct {
	ID         int32       `json:"id"`
	StageID    pgtype.Int4 `json:"stage_id"`
	WaveNumber int32       `json:"wave_number"`
}

type User struct {
	ID           uuid.UUID        `json:"id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	CratedAt     pgtype.Timestamp `json:"crated_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Online       pgtype.Bool      `json:"online"`
}

type UserChapterProgress struct {
	UserID      uuid.UUID        `json:"user_id"`
	ChapterID   int32            `json:"chapter_id"`
	IsUnlocked  pgtype.Bool      `json:"is_unlocked"`
	IsBeaten    pgtype.Bool      `json:"is_beaten"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type UserCompletedStage struct {
	UserID      uuid.UUID        `json:"user_id"`
	StageID     int32            `json:"stage_id"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type UserDigibank struct {
	UserID    uuid.UUID   `json:"user_id"`
	DigimonID pgtype.UUID `json:"digimon_id"`
	BankSlot  int32       `json:"bank_slot"`
}

type UserDigimon struct {
	ID            uuid.UUID        `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	BaseID        pgtype.Int4      `json:"base_id"`
	Nickname      pgtype.Text      `json:"nickname"`
	Level         pgtype.Int4      `json:"level"`
	Exp           pgtype.Int4      `json:"exp"`
	Friendship    pgtype.Int4      `json:"friendship"`
	IsStarter     pgtype.Bool      `json:"is_starter"`
	IsLocked      pgtype.Bool      `json:"is_locked"`
	CurrentHealth pgtype.Int4      `json:"current_health"`
	CurrentMana   pgtype.Int4      `json:"current_mana"`
	Health        pgtype.Int4      `json:"health"`
	Mana          pgtype.Int4      `json:"mana"`
	Attack        pgtype.Int4      `json:"attack"`
	Defense       pgtype.Int4      `json:"defense"`
	Speed         pgtype.Int4      `json:"speed"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type UserEpisodeProgress struct {
	UserID      uuid.UUID        `json:"user_id"`
	EpisodeID   int32            `json:"episode_id"`
	IsUnlocked  pgtype.Bool      `json:"is_unlocked"`
	IsBeaten    pgtype.Bool      `json:"is_beaten"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type UserInventory struct {
	ID       pgtype.Int4 `json:"id"`
	UserID   uuid.UUID   `json:"user_id"`
	ItemName string      `json:"item_name"`
	Quantity pgtype.Int4 `json:"quantity"`
}

type UserResource struct {
	UserID         uuid.UUID   `json:"user_id"`
	Level          pgtype.Int4 `json:"level"`
	Exp            pgtype.Int4 `json:"exp"`
	StaminaCurrent pgtype.Int4 `json:"stamina_current"`
	StaminaMax     pgtype.Int4 `json:"stamina_max"`
	Bits           pgtype.Int8 `json:"bits"`
	Yen            pgtype.Int8 `json:"yen"`
}

type UserTeam struct {
	UserID    uuid.UUID   `json:"user_id"`
	DigimonID pgtype.UUID `json:"digimon_id"`
	TeamSlot  int32       `json:"team_slot"`
}

type WaveEnemy struct {
	ID         int32       `json:"id"`
	WaveID     pgtype.Int4 `json:"wave_id"`
	EnemySlot  int32       `json:"enemy_slot"`
	EnemyID    pgtype.Int4 `json:"enemy_id"`
	EnemyLevel pgtype.Int4 `json:"enemy_level"`
}
