// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BaseDigimon struct {
	ID          int32
	Species     string
	BaseHealth  int32
	BaseAttack  int32
	BaseDefense int32
	BaseMana    int32
	BaseSpeed   int32
	Form        string
	Attribute   string
	Family      string
	Element     string
}

type Chapter struct {
	ID            int32
	ChapterName   string
	ChapterNumber string
	Description   pgtype.Text
	IsUnlocked    pgtype.Bool
}

type Episode struct {
	ID            int32
	ChapterID     pgtype.Int4
	EpisodeNumber int32
	EpisodeName   string
}

type Stage struct {
	ID            int32
	ChapterID     pgtype.Int4
	EpisodeID     pgtype.Int4
	StageNumber   int32
	StageName     string
	Description   pgtype.Text
	DefeatStageID pgtype.Int4
	TamerLevel    pgtype.Int4
	DropBits      pgtype.Int4
	DropExp       pgtype.Int4
	DropSexp      pgtype.Int4
	MaxWaves      pgtype.Int4
}

type StageItemDrop struct {
	ID      int32
	StageID pgtype.Int4
}

type StageWafe struct {
	ID         int32
	StageID    pgtype.Int4
	WaveNumber int32
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	CratedAt     pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
	Online       pgtype.Bool
}

type UserChapterProgress struct {
	UserID      uuid.UUID
	ChapterID   int32
	IsUnlocked  pgtype.Bool
	IsBeaten    pgtype.Bool
	CompletedAt pgtype.Timestamp
}

type UserCompletedStage struct {
	UserID      uuid.UUID
	StageID     int32
	CompletedAt pgtype.Timestamp
}

type UserDigibank struct {
	UserID    uuid.UUID
	DigimonID pgtype.UUID
	BankSlot  int32
}

type UserDigimon struct {
	ID            uuid.UUID
	UserID        pgtype.UUID
	BaseID        pgtype.Int4
	Nickname      pgtype.Text
	Level         pgtype.Int4
	Exp           pgtype.Int4
	Friendship    pgtype.Int4
	IsStarter     pgtype.Bool
	IsLocked      pgtype.Bool
	CurrentHealth pgtype.Int4
	CurrentMana   pgtype.Int4
	Health        pgtype.Int4
	Mana          pgtype.Int4
	Attack        pgtype.Int4
	Defense       pgtype.Int4
	Speed         pgtype.Int4
	CreatedAt     pgtype.Timestamp
}

type UserEpisodeProgress struct {
	UserID      uuid.UUID
	EpisodeID   int32
	IsUnlocked  pgtype.Bool
	IsBeaten    pgtype.Bool
	CompletedAt pgtype.Timestamp
}

type UserInventory struct {
	ID       pgtype.Int4
	UserID   uuid.UUID
	ItemName string
	Quantity pgtype.Int4
}

type UserResource struct {
	UserID         uuid.UUID
	Level          pgtype.Int4
	Exp            pgtype.Int4
	StaminaCurrent pgtype.Int4
	StaminaMax     pgtype.Int4
	Bits           pgtype.Int8
	Yen            pgtype.Int8
}

type UserTeam struct {
	UserID    uuid.UUID
	DigimonID pgtype.UUID
	TeamSlot  int32
}

type WaveEnemy struct {
	ID         int32
	WaveID     pgtype.Int4
	EnemySlot  int32
	EnemyID    pgtype.Int4
	EnemyLevel pgtype.Int4
}
