// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddDigimonToTeam(ctx context.Context, arg AddDigimonToTeamParams) error
	AddUserBits(ctx context.Context, arg AddUserBitsParams) error
	CheckUserChapterCompletion(ctx context.Context, arg CheckUserChapterCompletionParams) (CheckUserChapterCompletionRow, error)
	ClearTeamSlot(ctx context.Context, arg ClearTeamSlotParams) error
	CompleteStage(ctx context.Context, arg CompleteStageParams) error
	CompleteUserChapter(ctx context.Context, arg CompleteUserChapterParams) error
	CreatePlayerResources(ctx context.Context, userID uuid.UUID) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserDigimon(ctx context.Context, arg CreateUserDigimonParams) (UserDigimon, error)
	GetAllBaseDigimon(ctx context.Context) ([]BaseDigimon, error)
	GetAllUserDigimon(ctx context.Context, id uuid.UUID) ([]UserDigimon, error)
	GetAvailableEpisodesByChapterId(ctx context.Context, arg GetAvailableEpisodesByChapterIdParams) ([]Episode, error)
	GetAvailableStages(ctx context.Context, userID uuid.UUID) ([]GetAvailableStagesRow, error)
	GetAvailableStagesByEpisodeId(ctx context.Context, arg GetAvailableStagesByEpisodeIdParams) ([]Stage, error)
	GetBaseDigimon(ctx context.Context, id int32) (BaseDigimon, error)
	GetBaseDigimonBySpecies(ctx context.Context, species string) (BaseDigimon, error)
	GetCompletedStages(ctx context.Context, userID uuid.UUID) ([]UserCompletedStage, error)
	GetStageById(ctx context.Context, id int32) (GetStageByIdRow, error)
	GetStageWaves(ctx context.Context, id int32) ([]GetStageWavesRow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserDigibank(ctx context.Context, userID uuid.UUID) ([]GetUserDigibankRow, error)
	GetUserDigimon(ctx context.Context, arg GetUserDigimonParams) (UserDigimon, error)
	GetUserTeam(ctx context.Context, userID uuid.UUID) ([]GetUserTeamRow, error)
	GetUserUnlockedChapters(ctx context.Context, userID uuid.UUID) ([]GetUserUnlockedChaptersRow, error)
	GetUserWithResources(ctx context.Context, id uuid.UUID) (GetUserWithResourcesRow, error)
	RemoveDigimonFromTeam(ctx context.Context, arg RemoveDigimonFromTeamParams) error
	UnlockUserChapter(ctx context.Context, arg UnlockUserChapterParams) error
}

var _ Querier = (*Queries)(nil)
