// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: client.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketType int32

const (
	PacketType_UNKOWN                 PacketType = 0
	PacketType_AUTHENTICATION_REQUEST PacketType = 1
	// User
	PacketType_CHAPTER_DATA_REQUEST        PacketType = 2
	PacketType_EPISODES_BY_CHAPTER_REQUEST PacketType = 3
	PacketType_DIGIMON_SELECTED            PacketType = 4
	// Dialogue
	PacketType_DIALOGUE_CHOICE_SELECTED PacketType = 5
	PacketType_DIALOGUE_FINISHED        PacketType = 6
	// Digimon
	PacketType_VIEW_DIGIBANK_REQUEST PacketType = 8
	PacketType_VIEW_DIGIMON_REQUEST  PacketType = 9
	PacketType_DEVELOPMENT           PacketType = 999
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0:   "UNKOWN",
		1:   "AUTHENTICATION_REQUEST",
		2:   "CHAPTER_DATA_REQUEST",
		3:   "EPISODES_BY_CHAPTER_REQUEST",
		4:   "DIGIMON_SELECTED",
		5:   "DIALOGUE_CHOICE_SELECTED",
		6:   "DIALOGUE_FINISHED",
		8:   "VIEW_DIGIBANK_REQUEST",
		9:   "VIEW_DIGIMON_REQUEST",
		999: "DEVELOPMENT",
	}
	PacketType_value = map[string]int32{
		"UNKOWN":                      0,
		"AUTHENTICATION_REQUEST":      1,
		"CHAPTER_DATA_REQUEST":        2,
		"EPISODES_BY_CHAPTER_REQUEST": 3,
		"DIGIMON_SELECTED":            4,
		"DIALOGUE_CHOICE_SELECTED":    5,
		"DIALOGUE_FINISHED":           6,
		"VIEW_DIGIBANK_REQUEST":       8,
		"VIEW_DIGIMON_REQUEST":        9,
		"DEVELOPMENT":                 999,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type AuthenticationType int32

const (
	AuthenticationType_LOGIN    AuthenticationType = 0
	AuthenticationType_REGISTER AuthenticationType = 1
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "LOGIN",
		1: "REGISTER",
	}
	AuthenticationType_value = map[string]int32{
		"LOGIN":    0,
		"REGISTER": 1,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[1].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[1]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

type FromClientToServer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PacketType PacketType             `protobuf:"varint,1,opt,name=packet_type,json=packetType,proto3,enum=packets.PacketType" json:"packet_type,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FromClientToServer_AuthenticationRequest
	//	*FromClientToServer_EpisodesByChapterRequest
	//	*FromClientToServer_DigimonSelected
	//	*FromClientToServer_DialogueChoiceSelected
	//	*FromClientToServer_DialogueFinished
	//	*FromClientToServer_Dev
	Payload       isFromClientToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClientToServer) Reset() {
	*x = FromClientToServer{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClientToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClientToServer) ProtoMessage() {}

func (x *FromClientToServer) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClientToServer.ProtoReflect.Descriptor instead.
func (*FromClientToServer) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *FromClientToServer) GetPacketType() PacketType {
	if x != nil {
		return x.PacketType
	}
	return PacketType_UNKOWN
}

func (x *FromClientToServer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FromClientToServer) GetPayload() isFromClientToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FromClientToServer) GetAuthenticationRequest() *AuthenticationRequest {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_AuthenticationRequest); ok {
			return x.AuthenticationRequest
		}
	}
	return nil
}

func (x *FromClientToServer) GetEpisodesByChapterRequest() *EpisodesByChapterRequest {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_EpisodesByChapterRequest); ok {
			return x.EpisodesByChapterRequest
		}
	}
	return nil
}

func (x *FromClientToServer) GetDigimonSelected() *DigimonSelected {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DigimonSelected); ok {
			return x.DigimonSelected
		}
	}
	return nil
}

func (x *FromClientToServer) GetDialogueChoiceSelected() *DialogueChoiceSelected {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DialogueChoiceSelected); ok {
			return x.DialogueChoiceSelected
		}
	}
	return nil
}

func (x *FromClientToServer) GetDialogueFinished() *DialogueFinished {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DialogueFinished); ok {
			return x.DialogueFinished
		}
	}
	return nil
}

func (x *FromClientToServer) GetDev() *DevelopmentPacket {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_Dev); ok {
			return x.Dev
		}
	}
	return nil
}

type isFromClientToServer_Payload interface {
	isFromClientToServer_Payload()
}

type FromClientToServer_AuthenticationRequest struct {
	AuthenticationRequest *AuthenticationRequest `protobuf:"bytes,10,opt,name=authentication_request,json=authenticationRequest,proto3,oneof"`
}

type FromClientToServer_EpisodesByChapterRequest struct {
	EpisodesByChapterRequest *EpisodesByChapterRequest `protobuf:"bytes,11,opt,name=episodes_by_chapter_request,json=episodesByChapterRequest,proto3,oneof"`
}

type FromClientToServer_DigimonSelected struct {
	DigimonSelected *DigimonSelected `protobuf:"bytes,12,opt,name=digimon_selected,json=digimonSelected,proto3,oneof"`
}

type FromClientToServer_DialogueChoiceSelected struct {
	DialogueChoiceSelected *DialogueChoiceSelected `protobuf:"bytes,13,opt,name=dialogue_choice_selected,json=dialogueChoiceSelected,proto3,oneof"`
}

type FromClientToServer_DialogueFinished struct {
	DialogueFinished *DialogueFinished `protobuf:"bytes,14,opt,name=dialogue_finished,json=dialogueFinished,proto3,oneof"`
}

type FromClientToServer_Dev struct {
	Dev *DevelopmentPacket `protobuf:"bytes,9999,opt,name=dev,proto3,oneof"`
}

func (*FromClientToServer_AuthenticationRequest) isFromClientToServer_Payload() {}

func (*FromClientToServer_EpisodesByChapterRequest) isFromClientToServer_Payload() {}

func (*FromClientToServer_DigimonSelected) isFromClientToServer_Payload() {}

func (*FromClientToServer_DialogueChoiceSelected) isFromClientToServer_Payload() {}

func (*FromClientToServer_DialogueFinished) isFromClientToServer_Payload() {}

func (*FromClientToServer_Dev) isFromClientToServer_Payload() {}

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AuthenticationType     `protobuf:"varint,1,opt,name=type,proto3,enum=packets.AuthenticationType" json:"type,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticationRequest) GetType() AuthenticationType {
	if x != nil {
		return x.Type
	}
	return AuthenticationType_LOGIN
}

func (x *AuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EpisodesByChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int32                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodesByChapterRequest) Reset() {
	*x = EpisodesByChapterRequest{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodesByChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodesByChapterRequest) ProtoMessage() {}

func (x *EpisodesByChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodesByChapterRequest.ProtoReflect.Descriptor instead.
func (*EpisodesByChapterRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *EpisodesByChapterRequest) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

type DigimonSelected struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DigimonSpecies string                 `protobuf:"bytes,1,opt,name=digimon_species,json=digimonSpecies,proto3" json:"digimon_species,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DigimonSelected) Reset() {
	*x = DigimonSelected{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonSelected) ProtoMessage() {}

func (x *DigimonSelected) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonSelected.ProtoReflect.Descriptor instead.
func (*DigimonSelected) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *DigimonSelected) GetDigimonSpecies() string {
	if x != nil {
		return x.DigimonSpecies
	}
	return ""
}

type DialogueFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogueFinished) Reset() {
	*x = DialogueFinished{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueFinished) ProtoMessage() {}

func (x *DialogueFinished) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueFinished.ProtoReflect.Descriptor instead.
func (*DialogueFinished) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *DialogueFinished) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

type DialogueChoiceSelected struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DialogueId       string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	DialogueChoiceId int32                  `protobuf:"varint,2,opt,name=dialogue_choice_id,json=dialogueChoiceId,proto3" json:"dialogue_choice_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DialogueChoiceSelected) Reset() {
	*x = DialogueChoiceSelected{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueChoiceSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueChoiceSelected) ProtoMessage() {}

func (x *DialogueChoiceSelected) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueChoiceSelected.ProtoReflect.Descriptor instead.
func (*DialogueChoiceSelected) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *DialogueChoiceSelected) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

func (x *DialogueChoiceSelected) GetDialogueChoiceId() int32 {
	if x != nil {
		return x.DialogueChoiceId
	}
	return 0
}

type DevelopmentPacket struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AddDigimonToTeam bool                   `protobuf:"varint,1,opt,name=add_digimon_to_team,json=addDigimonToTeam,proto3" json:"add_digimon_to_team,omitempty"`
	ResetAccount     bool                   `protobuf:"varint,2,opt,name=reset_account,json=resetAccount,proto3" json:"reset_account,omitempty"`
	StarterSpecies   string                 `protobuf:"bytes,3,opt,name=starter_species,json=starterSpecies,proto3" json:"starter_species,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DevelopmentPacket) Reset() {
	*x = DevelopmentPacket{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevelopmentPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevelopmentPacket) ProtoMessage() {}

func (x *DevelopmentPacket) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevelopmentPacket.ProtoReflect.Descriptor instead.
func (*DevelopmentPacket) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *DevelopmentPacket) GetAddDigimonToTeam() bool {
	if x != nil {
		return x.AddDigimonToTeam
	}
	return false
}

func (x *DevelopmentPacket) GetResetAccount() bool {
	if x != nil {
		return x.ResetAccount
	}
	return false
}

func (x *DevelopmentPacket) GetStarterSpecies() string {
	if x != nil {
		return x.StarterSpecies
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\apackets\"\xca\x04\n" +
	"\x12FromClientToServer\x124\n" +
	"\vpacket_type\x18\x01 \x01(\x0e2\x13.packets.PacketTypeR\n" +
	"packetType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12W\n" +
	"\x16authentication_request\x18\n" +
	" \x01(\v2\x1e.packets.AuthenticationRequestH\x00R\x15authenticationRequest\x12b\n" +
	"\x1bepisodes_by_chapter_request\x18\v \x01(\v2!.packets.EpisodesByChapterRequestH\x00R\x18episodesByChapterRequest\x12E\n" +
	"\x10digimon_selected\x18\f \x01(\v2\x18.packets.DigimonSelectedH\x00R\x0fdigimonSelected\x12[\n" +
	"\x18dialogue_choice_selected\x18\r \x01(\v2\x1f.packets.DialogueChoiceSelectedH\x00R\x16dialogueChoiceSelected\x12H\n" +
	"\x11dialogue_finished\x18\x0e \x01(\v2\x19.packets.DialogueFinishedH\x00R\x10dialogueFinished\x12/\n" +
	"\x03dev\x18\x8fN \x01(\v2\x1a.packets.DevelopmentPacketH\x00R\x03devB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\x15AuthenticationRequest\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.packets.AuthenticationTypeR\x04type\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"9\n" +
	"\x18EpisodesByChapterRequest\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x05R\tchapterId\":\n" +
	"\x0fDigimonSelected\x12'\n" +
	"\x0fdigimon_species\x18\x01 \x01(\tR\x0edigimonSpecies\"3\n" +
	"\x10DialogueFinished\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\"g\n" +
	"\x16DialogueChoiceSelected\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\x12,\n" +
	"\x12dialogue_choice_id\x18\x02 \x01(\x05R\x10dialogueChoiceId\"\x90\x01\n" +
	"\x11DevelopmentPacket\x12-\n" +
	"\x13add_digimon_to_team\x18\x01 \x01(\bR\x10addDigimonToTeam\x12#\n" +
	"\rreset_account\x18\x02 \x01(\bR\fresetAccount\x12'\n" +
	"\x0fstarter_species\x18\x03 \x01(\tR\x0estarterSpecies*\x81\x02\n" +
	"\n" +
	"PacketType\x12\n" +
	"\n" +
	"\x06UNKOWN\x10\x00\x12\x1a\n" +
	"\x16AUTHENTICATION_REQUEST\x10\x01\x12\x18\n" +
	"\x14CHAPTER_DATA_REQUEST\x10\x02\x12\x1f\n" +
	"\x1bEPISODES_BY_CHAPTER_REQUEST\x10\x03\x12\x14\n" +
	"\x10DIGIMON_SELECTED\x10\x04\x12\x1c\n" +
	"\x18DIALOGUE_CHOICE_SELECTED\x10\x05\x12\x15\n" +
	"\x11DIALOGUE_FINISHED\x10\x06\x12\x19\n" +
	"\x15VIEW_DIGIBANK_REQUEST\x10\b\x12\x18\n" +
	"\x14VIEW_DIGIMON_REQUEST\x10\t\x12\x10\n" +
	"\vDEVELOPMENT\x10\xe7\a*-\n" +
	"\x12AuthenticationType\x12\t\n" +
	"\x05LOGIN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01B\rZ\vpkg/packetsb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_proto_goTypes = []any{
	(PacketType)(0),                  // 0: packets.PacketType
	(AuthenticationType)(0),          // 1: packets.AuthenticationType
	(*FromClientToServer)(nil),       // 2: packets.FromClientToServer
	(*AuthenticationRequest)(nil),    // 3: packets.AuthenticationRequest
	(*EpisodesByChapterRequest)(nil), // 4: packets.EpisodesByChapterRequest
	(*DigimonSelected)(nil),          // 5: packets.DigimonSelected
	(*DialogueFinished)(nil),         // 6: packets.DialogueFinished
	(*DialogueChoiceSelected)(nil),   // 7: packets.DialogueChoiceSelected
	(*DevelopmentPacket)(nil),        // 8: packets.DevelopmentPacket
}
var file_client_proto_depIdxs = []int32{
	0, // 0: packets.FromClientToServer.packet_type:type_name -> packets.PacketType
	3, // 1: packets.FromClientToServer.authentication_request:type_name -> packets.AuthenticationRequest
	4, // 2: packets.FromClientToServer.episodes_by_chapter_request:type_name -> packets.EpisodesByChapterRequest
	5, // 3: packets.FromClientToServer.digimon_selected:type_name -> packets.DigimonSelected
	7, // 4: packets.FromClientToServer.dialogue_choice_selected:type_name -> packets.DialogueChoiceSelected
	6, // 5: packets.FromClientToServer.dialogue_finished:type_name -> packets.DialogueFinished
	8, // 6: packets.FromClientToServer.dev:type_name -> packets.DevelopmentPacket
	1, // 7: packets.AuthenticationRequest.type:type_name -> packets.AuthenticationType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_client_proto_msgTypes[0].OneofWrappers = []any{
		(*FromClientToServer_AuthenticationRequest)(nil),
		(*FromClientToServer_EpisodesByChapterRequest)(nil),
		(*FromClientToServer_DigimonSelected)(nil),
		(*FromClientToServer_DialogueChoiceSelected)(nil),
		(*FromClientToServer_DialogueFinished)(nil),
		(*FromClientToServer_Dev)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
