// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationType int32

const (
	AuthenticationType_LOGIN    AuthenticationType = 0
	AuthenticationType_REGISTER AuthenticationType = 1
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "LOGIN",
		1: "REGISTER",
	}
	AuthenticationType_value = map[string]int32{
		"LOGIN":    0,
		"REGISTER": 1,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type PacketType int32

const (
	PacketType_UNKOWN                 PacketType = 0
	PacketType_AUTHENTICATION_REQUEST PacketType = 1
	// User
	PacketType_CHAPTER_DATA_REQUEST        PacketType = 2
	PacketType_EPISODES_BY_CHAPTER_REQUEST PacketType = 3
	PacketType_DIGIMON_SELECTED            PacketType = 4
	// Dialogue
	PacketType_DIALOGUE_CHOICE_SELECTED PacketType = 5
	PacketType_DIALOGUE_FINISHED        PacketType = 6
	PacketType_DEVELOPMENT              PacketType = 999
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0:   "UNKOWN",
		1:   "AUTHENTICATION_REQUEST",
		2:   "CHAPTER_DATA_REQUEST",
		3:   "EPISODES_BY_CHAPTER_REQUEST",
		4:   "DIGIMON_SELECTED",
		5:   "DIALOGUE_CHOICE_SELECTED",
		6:   "DIALOGUE_FINISHED",
		999: "DEVELOPMENT",
	}
	PacketType_value = map[string]int32{
		"UNKOWN":                      0,
		"AUTHENTICATION_REQUEST":      1,
		"CHAPTER_DATA_REQUEST":        2,
		"EPISODES_BY_CHAPTER_REQUEST": 3,
		"DIGIMON_SELECTED":            4,
		"DIALOGUE_CHOICE_SELECTED":    5,
		"DIALOGUE_FINISHED":           6,
		"DEVELOPMENT":                 999,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

type ErrorCode int32

const (
	ErrorCode_UNKOWN_ERROR ErrorCode = 0
	// Authentication
	ErrorCode_INVALID_CREDENTIALS        ErrorCode = 1
	ErrorCode_USERNAME_TAKEN             ErrorCode = 2
	ErrorCode_USERNAME_TOO_SHORT_OR_LONG ErrorCode = 3
	ErrorCode_PASSWORD_TOO_SHORT         ErrorCode = 4 //USER_NOT_FOUND = 4;
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKOWN_ERROR",
		1: "INVALID_CREDENTIALS",
		2: "USERNAME_TAKEN",
		3: "USERNAME_TOO_SHORT_OR_LONG",
		4: "PASSWORD_TOO_SHORT",
	}
	ErrorCode_value = map[string]int32{
		"UNKOWN_ERROR":               0,
		"INVALID_CREDENTIALS":        1,
		"USERNAME_TAKEN":             2,
		"USERNAME_TOO_SHORT_OR_LONG": 3,
		"PASSWORD_TOO_SHORT":         4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[2].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[2]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

type FromClientToServer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PacketType PacketType             `protobuf:"varint,1,opt,name=packet_type,json=packetType,proto3,enum=packets.PacketType" json:"packet_type,omitempty"`
	UserId     string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FromClientToServer_AuthenticationRequest
	//	*FromClientToServer_EpisodesByChapterRequest
	//	*FromClientToServer_DigimonSelected
	//	*FromClientToServer_DialogueChoiceSelected
	//	*FromClientToServer_DialogueFinished
	//	*FromClientToServer_Dev
	Payload       isFromClientToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClientToServer) Reset() {
	*x = FromClientToServer{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClientToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClientToServer) ProtoMessage() {}

func (x *FromClientToServer) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClientToServer.ProtoReflect.Descriptor instead.
func (*FromClientToServer) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *FromClientToServer) GetPacketType() PacketType {
	if x != nil {
		return x.PacketType
	}
	return PacketType_UNKOWN
}

func (x *FromClientToServer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FromClientToServer) GetPayload() isFromClientToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FromClientToServer) GetAuthenticationRequest() *AuthenticationRequest {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_AuthenticationRequest); ok {
			return x.AuthenticationRequest
		}
	}
	return nil
}

func (x *FromClientToServer) GetEpisodesByChapterRequest() *EpisodesByChapterRequest {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_EpisodesByChapterRequest); ok {
			return x.EpisodesByChapterRequest
		}
	}
	return nil
}

func (x *FromClientToServer) GetDigimonSelected() *DigimonSelected {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DigimonSelected); ok {
			return x.DigimonSelected
		}
	}
	return nil
}

func (x *FromClientToServer) GetDialogueChoiceSelected() *DialogueChoiceSelected {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DialogueChoiceSelected); ok {
			return x.DialogueChoiceSelected
		}
	}
	return nil
}

func (x *FromClientToServer) GetDialogueFinished() *DialogueFinished {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_DialogueFinished); ok {
			return x.DialogueFinished
		}
	}
	return nil
}

func (x *FromClientToServer) GetDev() *DevelopmentPacket {
	if x != nil {
		if x, ok := x.Payload.(*FromClientToServer_Dev); ok {
			return x.Dev
		}
	}
	return nil
}

type isFromClientToServer_Payload interface {
	isFromClientToServer_Payload()
}

type FromClientToServer_AuthenticationRequest struct {
	AuthenticationRequest *AuthenticationRequest `protobuf:"bytes,10,opt,name=authentication_request,json=authenticationRequest,proto3,oneof"`
}

type FromClientToServer_EpisodesByChapterRequest struct {
	EpisodesByChapterRequest *EpisodesByChapterRequest `protobuf:"bytes,11,opt,name=episodes_by_chapter_request,json=episodesByChapterRequest,proto3,oneof"`
}

type FromClientToServer_DigimonSelected struct {
	DigimonSelected *DigimonSelected `protobuf:"bytes,12,opt,name=digimon_selected,json=digimonSelected,proto3,oneof"`
}

type FromClientToServer_DialogueChoiceSelected struct {
	DialogueChoiceSelected *DialogueChoiceSelected `protobuf:"bytes,13,opt,name=dialogue_choice_selected,json=dialogueChoiceSelected,proto3,oneof"`
}

type FromClientToServer_DialogueFinished struct {
	DialogueFinished *DialogueFinished `protobuf:"bytes,14,opt,name=dialogue_finished,json=dialogueFinished,proto3,oneof"`
}

type FromClientToServer_Dev struct {
	Dev *DevelopmentPacket `protobuf:"bytes,9999,opt,name=dev,proto3,oneof"`
}

func (*FromClientToServer_AuthenticationRequest) isFromClientToServer_Payload() {}

func (*FromClientToServer_EpisodesByChapterRequest) isFromClientToServer_Payload() {}

func (*FromClientToServer_DigimonSelected) isFromClientToServer_Payload() {}

func (*FromClientToServer_DialogueChoiceSelected) isFromClientToServer_Payload() {}

func (*FromClientToServer_DialogueFinished) isFromClientToServer_Payload() {}

func (*FromClientToServer_Dev) isFromClientToServer_Payload() {}

type FromServerToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FromServerToClient_WebsocketId
	//	*FromServerToClient_ErrorResponse
	//	*FromServerToClient_AuthenticationResponse
	//	*FromServerToClient_ChapterDataResponse
	//	*FromServerToClient_EpisodeDataResponse
	//	*FromServerToClient_DialogueTrigger
	Payload       isFromServerToClient_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromServerToClient) Reset() {
	*x = FromServerToClient{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromServerToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromServerToClient) ProtoMessage() {}

func (x *FromServerToClient) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromServerToClient.ProtoReflect.Descriptor instead.
func (*FromServerToClient) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *FromServerToClient) GetPayload() isFromServerToClient_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FromServerToClient) GetWebsocketId() *WebsocketIDResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_WebsocketId); ok {
			return x.WebsocketId
		}
	}
	return nil
}

func (x *FromServerToClient) GetErrorResponse() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_ErrorResponse); ok {
			return x.ErrorResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetAuthenticationResponse() *AuthenticationResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_AuthenticationResponse); ok {
			return x.AuthenticationResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetChapterDataResponse() *AccessibleChapterResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_ChapterDataResponse); ok {
			return x.ChapterDataResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetEpisodeDataResponse() *AccessibleEpisodesResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_EpisodeDataResponse); ok {
			return x.EpisodeDataResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetDialogueTrigger() *DialogueTrigger {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_DialogueTrigger); ok {
			return x.DialogueTrigger
		}
	}
	return nil
}

type isFromServerToClient_Payload interface {
	isFromServerToClient_Payload()
}

type FromServerToClient_WebsocketId struct {
	WebsocketId *WebsocketIDResponse `protobuf:"bytes,1,opt,name=websocket_id,json=websocketId,proto3,oneof"`
}

type FromServerToClient_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type FromServerToClient_AuthenticationResponse struct {
	AuthenticationResponse *AuthenticationResponse `protobuf:"bytes,3,opt,name=authentication_response,json=authenticationResponse,proto3,oneof"`
}

type FromServerToClient_ChapterDataResponse struct {
	ChapterDataResponse *AccessibleChapterResponse `protobuf:"bytes,4,opt,name=chapter_data_response,json=chapterDataResponse,proto3,oneof"`
}

type FromServerToClient_EpisodeDataResponse struct {
	EpisodeDataResponse *AccessibleEpisodesResponse `protobuf:"bytes,5,opt,name=episode_data_response,json=episodeDataResponse,proto3,oneof"`
}

type FromServerToClient_DialogueTrigger struct {
	DialogueTrigger *DialogueTrigger `protobuf:"bytes,6,opt,name=dialogue_trigger,json=dialogueTrigger,proto3,oneof"`
}

func (*FromServerToClient_WebsocketId) isFromServerToClient_Payload() {}

func (*FromServerToClient_ErrorResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_AuthenticationResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_ChapterDataResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_EpisodeDataResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_DialogueTrigger) isFromServerToClient_Payload() {}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=packets.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKOWN_ERROR
}

// Authentication
type WebsocketIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketIDResponse) Reset() {
	*x = WebsocketIDResponse{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketIDResponse) ProtoMessage() {}

func (x *WebsocketIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketIDResponse.ProtoReflect.Descriptor instead.
func (*WebsocketIDResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *WebsocketIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AuthenticationType     `protobuf:"varint,1,opt,name=type,proto3,enum=packets.AuthenticationType" json:"type,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationRequest) Reset() {
	*x = AuthenticationRequest{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationRequest) ProtoMessage() {}

func (x *AuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationRequest.ProtoReflect.Descriptor instead.
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticationRequest) GetType() AuthenticationType {
	if x != nil {
		return x.Type
	}
	return AuthenticationType_LOGIN
}

func (x *AuthenticationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserData        *UserData              `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	DialogueTrigger *DialogueTrigger       `protobuf:"bytes,3,opt,name=dialogue_trigger,json=dialogueTrigger,proto3" json:"dialogue_trigger,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *AuthenticationResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthenticationResponse) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *AuthenticationResponse) GetDialogueTrigger() *DialogueTrigger {
	if x != nil {
		return x.DialogueTrigger
	}
	return nil
}

// General Info
type UserData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Level          int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp            int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Bits           int64                  `protobuf:"varint,4,opt,name=bits,proto3" json:"bits,omitempty"`
	Yen            int64                  `protobuf:"varint,5,opt,name=yen,proto3" json:"yen,omitempty"`
	StaminaCurrent int32                  `protobuf:"varint,6,opt,name=stamina_current,json=staminaCurrent,proto3" json:"stamina_current,omitempty"`
	StaminaMax     int32                  `protobuf:"varint,7,opt,name=stamina_max,json=staminaMax,proto3" json:"stamina_max,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserData) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *UserData) GetYen() int64 {
	if x != nil {
		return x.Yen
	}
	return 0
}

func (x *UserData) GetStaminaCurrent() int32 {
	if x != nil {
		return x.StaminaCurrent
	}
	return 0
}

func (x *UserData) GetStaminaMax() int32 {
	if x != nil {
		return x.StaminaMax
	}
	return 0
}

// Stages
type AccessibleChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*ChapterData         `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessibleChapterResponse) Reset() {
	*x = AccessibleChapterResponse{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessibleChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessibleChapterResponse) ProtoMessage() {}

func (x *AccessibleChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessibleChapterResponse.ProtoReflect.Descriptor instead.
func (*AccessibleChapterResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *AccessibleChapterResponse) GetChapters() []*ChapterData {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type ChapterData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChapterId          int32                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	ChapterNumber      int32                  `protobuf:"varint,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	ChapterName        string                 `protobuf:"bytes,3,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	ChapterDescription string                 `protobuf:"bytes,4,opt,name=chapter_description,json=chapterDescription,proto3" json:"chapter_description,omitempty"`
	IsUnlocked         bool                   `protobuf:"varint,5,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	IsBeaten           bool                   `protobuf:"varint,6,opt,name=is_beaten,json=isBeaten,proto3" json:"is_beaten,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChapterData) Reset() {
	*x = ChapterData{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterData) ProtoMessage() {}

func (x *ChapterData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterData.ProtoReflect.Descriptor instead.
func (*ChapterData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *ChapterData) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ChapterData) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *ChapterData) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *ChapterData) GetChapterDescription() string {
	if x != nil {
		return x.ChapterDescription
	}
	return ""
}

func (x *ChapterData) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *ChapterData) GetIsBeaten() bool {
	if x != nil {
		return x.IsBeaten
	}
	return false
}

type EpisodesByChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int32                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodesByChapterRequest) Reset() {
	*x = EpisodesByChapterRequest{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodesByChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodesByChapterRequest) ProtoMessage() {}

func (x *EpisodesByChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodesByChapterRequest.ProtoReflect.Descriptor instead.
func (*EpisodesByChapterRequest) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *EpisodesByChapterRequest) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

type AccessibleEpisodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episodes      []*EpisodeData         `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessibleEpisodesResponse) Reset() {
	*x = AccessibleEpisodesResponse{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessibleEpisodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessibleEpisodesResponse) ProtoMessage() {}

func (x *AccessibleEpisodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessibleEpisodesResponse.ProtoReflect.Descriptor instead.
func (*AccessibleEpisodesResponse) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *AccessibleEpisodesResponse) GetEpisodes() []*EpisodeData {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type EpisodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     int32                  `protobuf:"varint,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	EpisodeNumber int32                  `protobuf:"varint,2,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	EpisodeName   string                 `protobuf:"bytes,3,opt,name=episode_name,json=episodeName,proto3" json:"episode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeData) Reset() {
	*x = EpisodeData{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeData) ProtoMessage() {}

func (x *EpisodeData) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeData.ProtoReflect.Descriptor instead.
func (*EpisodeData) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *EpisodeData) GetEpisodeId() int32 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *EpisodeData) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *EpisodeData) GetEpisodeName() string {
	if x != nil {
		return x.EpisodeName
	}
	return ""
}

type DialogueTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogueTrigger) Reset() {
	*x = DialogueTrigger{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueTrigger) ProtoMessage() {}

func (x *DialogueTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueTrigger.ProtoReflect.Descriptor instead.
func (*DialogueTrigger) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *DialogueTrigger) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

type DialogueFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogueFinished) Reset() {
	*x = DialogueFinished{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueFinished) ProtoMessage() {}

func (x *DialogueFinished) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueFinished.ProtoReflect.Descriptor instead.
func (*DialogueFinished) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *DialogueFinished) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

type DialogueChoiceSelected struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DialogueId       string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	DialogueChoiceId string                 `protobuf:"bytes,2,opt,name=dialogue_choice_id,json=dialogueChoiceId,proto3" json:"dialogue_choice_id,omitempty"`
	DialogueMessage  string                 `protobuf:"bytes,3,opt,name=dialogue_message,json=dialogueMessage,proto3" json:"dialogue_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DialogueChoiceSelected) Reset() {
	*x = DialogueChoiceSelected{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueChoiceSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueChoiceSelected) ProtoMessage() {}

func (x *DialogueChoiceSelected) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueChoiceSelected.ProtoReflect.Descriptor instead.
func (*DialogueChoiceSelected) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *DialogueChoiceSelected) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

func (x *DialogueChoiceSelected) GetDialogueChoiceId() string {
	if x != nil {
		return x.DialogueChoiceId
	}
	return ""
}

func (x *DialogueChoiceSelected) GetDialogueMessage() string {
	if x != nil {
		return x.DialogueMessage
	}
	return ""
}

// DEVELOPMENT
type DigimonSelected struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DigimonSpecies string                 `protobuf:"bytes,1,opt,name=digimon_species,json=digimonSpecies,proto3" json:"digimon_species,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DigimonSelected) Reset() {
	*x = DigimonSelected{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonSelected) ProtoMessage() {}

func (x *DigimonSelected) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonSelected.ProtoReflect.Descriptor instead.
func (*DigimonSelected) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *DigimonSelected) GetDigimonSpecies() string {
	if x != nil {
		return x.DigimonSpecies
	}
	return ""
}

type DevelopmentPacket struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ADD_DIGIMON_TO_TEAM bool                   `protobuf:"varint,1,opt,name=ADD_DIGIMON_TO_TEAM,json=ADDDIGIMONTOTEAM,proto3" json:"ADD_DIGIMON_TO_TEAM,omitempty"`
	RESET_ACCOUNT       bool                   `protobuf:"varint,2,opt,name=RESET_ACCOUNT,json=RESETACCOUNT,proto3" json:"RESET_ACCOUNT,omitempty"`
	STARTER_SPECIES     string                 `protobuf:"bytes,3,opt,name=STARTER_SPECIES,json=STARTERSPECIES,proto3" json:"STARTER_SPECIES,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DevelopmentPacket) Reset() {
	*x = DevelopmentPacket{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevelopmentPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevelopmentPacket) ProtoMessage() {}

func (x *DevelopmentPacket) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevelopmentPacket.ProtoReflect.Descriptor instead.
func (*DevelopmentPacket) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *DevelopmentPacket) GetADD_DIGIMON_TO_TEAM() bool {
	if x != nil {
		return x.ADD_DIGIMON_TO_TEAM
	}
	return false
}

func (x *DevelopmentPacket) GetRESET_ACCOUNT() bool {
	if x != nil {
		return x.RESET_ACCOUNT
	}
	return false
}

func (x *DevelopmentPacket) GetSTARTER_SPECIES() string {
	if x != nil {
		return x.STARTER_SPECIES
	}
	return ""
}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\"\xca\x04\n" +
	"\x12FromClientToServer\x124\n" +
	"\vpacket_type\x18\x01 \x01(\x0e2\x13.packets.PacketTypeR\n" +
	"packetType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12W\n" +
	"\x16authentication_request\x18\n" +
	" \x01(\v2\x1e.packets.AuthenticationRequestH\x00R\x15authenticationRequest\x12b\n" +
	"\x1bepisodes_by_chapter_request\x18\v \x01(\v2!.packets.EpisodesByChapterRequestH\x00R\x18episodesByChapterRequest\x12E\n" +
	"\x10digimon_selected\x18\f \x01(\v2\x18.packets.DigimonSelectedH\x00R\x0fdigimonSelected\x12[\n" +
	"\x18dialogue_choice_selected\x18\r \x01(\v2\x1f.packets.DialogueChoiceSelectedH\x00R\x16dialogueChoiceSelected\x12H\n" +
	"\x11dialogue_finished\x18\x0e \x01(\v2\x19.packets.DialogueFinishedH\x00R\x10dialogueFinished\x12/\n" +
	"\x03dev\x18\x8fN \x01(\v2\x1a.packets.DevelopmentPacketH\x00R\x03devB\t\n" +
	"\apayload\"\xfb\x03\n" +
	"\x12FromServerToClient\x12A\n" +
	"\fwebsocket_id\x18\x01 \x01(\v2\x1c.packets.WebsocketIDResponseH\x00R\vwebsocketId\x12?\n" +
	"\x0eerror_response\x18\x02 \x01(\v2\x16.packets.ErrorResponseH\x00R\rerrorResponse\x12Z\n" +
	"\x17authentication_response\x18\x03 \x01(\v2\x1f.packets.AuthenticationResponseH\x00R\x16authenticationResponse\x12X\n" +
	"\x15chapter_data_response\x18\x04 \x01(\v2\".packets.AccessibleChapterResponseH\x00R\x13chapterDataResponse\x12Y\n" +
	"\x15episode_data_response\x18\x05 \x01(\v2#.packets.AccessibleEpisodesResponseH\x00R\x13episodeDataResponse\x12E\n" +
	"\x10dialogue_trigger\x18\x06 \x01(\v2\x18.packets.DialogueTriggerH\x00R\x0fdialogueTriggerB\t\n" +
	"\apayload\"7\n" +
	"\rErrorResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.packets.ErrorCodeR\x04code\"%\n" +
	"\x13WebsocketIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x01\n" +
	"\x15AuthenticationRequest\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.packets.AuthenticationTypeR\x04type\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\xb0\x01\n" +
	"\x16AuthenticationResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\tuser_data\x18\x02 \x01(\v2\x11.packets.UserDataR\buserData\x12C\n" +
	"\x10dialogue_trigger\x18\x03 \x01(\v2\x18.packets.DialogueTriggerR\x0fdialogueTrigger\"\xbe\x01\n" +
	"\bUserData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04bits\x18\x04 \x01(\x03R\x04bits\x12\x10\n" +
	"\x03yen\x18\x05 \x01(\x03R\x03yen\x12'\n" +
	"\x0fstamina_current\x18\x06 \x01(\x05R\x0estaminaCurrent\x12\x1f\n" +
	"\vstamina_max\x18\a \x01(\x05R\n" +
	"staminaMax\"M\n" +
	"\x19AccessibleChapterResponse\x120\n" +
	"\bchapters\x18\x01 \x03(\v2\x14.packets.ChapterDataR\bchapters\"\xe5\x01\n" +
	"\vChapterData\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x05R\tchapterId\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\x05R\rchapterNumber\x12!\n" +
	"\fchapter_name\x18\x03 \x01(\tR\vchapterName\x12/\n" +
	"\x13chapter_description\x18\x04 \x01(\tR\x12chapterDescription\x12\x1f\n" +
	"\vis_unlocked\x18\x05 \x01(\bR\n" +
	"isUnlocked\x12\x1b\n" +
	"\tis_beaten\x18\x06 \x01(\bR\bisBeaten\"9\n" +
	"\x18EpisodesByChapterRequest\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x05R\tchapterId\"N\n" +
	"\x1aAccessibleEpisodesResponse\x120\n" +
	"\bepisodes\x18\x01 \x03(\v2\x14.packets.EpisodeDataR\bepisodes\"v\n" +
	"\vEpisodeData\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\x05R\tepisodeId\x12%\n" +
	"\x0eepisode_number\x18\x02 \x01(\x05R\repisodeNumber\x12!\n" +
	"\fepisode_name\x18\x03 \x01(\tR\vepisodeName\"2\n" +
	"\x0fDialogueTrigger\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\"3\n" +
	"\x10DialogueFinished\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\"\x92\x01\n" +
	"\x16DialogueChoiceSelected\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\x12,\n" +
	"\x12dialogue_choice_id\x18\x02 \x01(\tR\x10dialogueChoiceId\x12)\n" +
	"\x10dialogue_message\x18\x03 \x01(\tR\x0fdialogueMessage\":\n" +
	"\x0fDigimonSelected\x12'\n" +
	"\x0fdigimon_species\x18\x01 \x01(\tR\x0edigimonSpecies\"\x90\x01\n" +
	"\x11DevelopmentPacket\x12-\n" +
	"\x13ADD_DIGIMON_TO_TEAM\x18\x01 \x01(\bR\x10ADDDIGIMONTOTEAM\x12#\n" +
	"\rRESET_ACCOUNT\x18\x02 \x01(\bR\fRESETACCOUNT\x12'\n" +
	"\x0fSTARTER_SPECIES\x18\x03 \x01(\tR\x0eSTARTERSPECIES*-\n" +
	"\x12AuthenticationType\x12\t\n" +
	"\x05LOGIN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01*\xcc\x01\n" +
	"\n" +
	"PacketType\x12\n" +
	"\n" +
	"\x06UNKOWN\x10\x00\x12\x1a\n" +
	"\x16AUTHENTICATION_REQUEST\x10\x01\x12\x18\n" +
	"\x14CHAPTER_DATA_REQUEST\x10\x02\x12\x1f\n" +
	"\x1bEPISODES_BY_CHAPTER_REQUEST\x10\x03\x12\x14\n" +
	"\x10DIGIMON_SELECTED\x10\x04\x12\x1c\n" +
	"\x18DIALOGUE_CHOICE_SELECTED\x10\x05\x12\x15\n" +
	"\x11DIALOGUE_FINISHED\x10\x06\x12\x10\n" +
	"\vDEVELOPMENT\x10\xe7\a*\x82\x01\n" +
	"\tErrorCode\x12\x10\n" +
	"\fUNKOWN_ERROR\x10\x00\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eUSERNAME_TAKEN\x10\x02\x12\x1e\n" +
	"\x1aUSERNAME_TOO_SHORT_OR_LONG\x10\x03\x12\x16\n" +
	"\x12PASSWORD_TOO_SHORT\x10\x04B\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_packets_proto_goTypes = []any{
	(AuthenticationType)(0),            // 0: packets.AuthenticationType
	(PacketType)(0),                    // 1: packets.PacketType
	(ErrorCode)(0),                     // 2: packets.ErrorCode
	(*FromClientToServer)(nil),         // 3: packets.FromClientToServer
	(*FromServerToClient)(nil),         // 4: packets.FromServerToClient
	(*ErrorResponse)(nil),              // 5: packets.ErrorResponse
	(*WebsocketIDResponse)(nil),        // 6: packets.WebsocketIDResponse
	(*AuthenticationRequest)(nil),      // 7: packets.AuthenticationRequest
	(*AuthenticationResponse)(nil),     // 8: packets.AuthenticationResponse
	(*UserData)(nil),                   // 9: packets.UserData
	(*AccessibleChapterResponse)(nil),  // 10: packets.AccessibleChapterResponse
	(*ChapterData)(nil),                // 11: packets.ChapterData
	(*EpisodesByChapterRequest)(nil),   // 12: packets.EpisodesByChapterRequest
	(*AccessibleEpisodesResponse)(nil), // 13: packets.AccessibleEpisodesResponse
	(*EpisodeData)(nil),                // 14: packets.EpisodeData
	(*DialogueTrigger)(nil),            // 15: packets.DialogueTrigger
	(*DialogueFinished)(nil),           // 16: packets.DialogueFinished
	(*DialogueChoiceSelected)(nil),     // 17: packets.DialogueChoiceSelected
	(*DigimonSelected)(nil),            // 18: packets.DigimonSelected
	(*DevelopmentPacket)(nil),          // 19: packets.DevelopmentPacket
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: packets.FromClientToServer.packet_type:type_name -> packets.PacketType
	7,  // 1: packets.FromClientToServer.authentication_request:type_name -> packets.AuthenticationRequest
	12, // 2: packets.FromClientToServer.episodes_by_chapter_request:type_name -> packets.EpisodesByChapterRequest
	18, // 3: packets.FromClientToServer.digimon_selected:type_name -> packets.DigimonSelected
	17, // 4: packets.FromClientToServer.dialogue_choice_selected:type_name -> packets.DialogueChoiceSelected
	16, // 5: packets.FromClientToServer.dialogue_finished:type_name -> packets.DialogueFinished
	19, // 6: packets.FromClientToServer.dev:type_name -> packets.DevelopmentPacket
	6,  // 7: packets.FromServerToClient.websocket_id:type_name -> packets.WebsocketIDResponse
	5,  // 8: packets.FromServerToClient.error_response:type_name -> packets.ErrorResponse
	8,  // 9: packets.FromServerToClient.authentication_response:type_name -> packets.AuthenticationResponse
	10, // 10: packets.FromServerToClient.chapter_data_response:type_name -> packets.AccessibleChapterResponse
	13, // 11: packets.FromServerToClient.episode_data_response:type_name -> packets.AccessibleEpisodesResponse
	15, // 12: packets.FromServerToClient.dialogue_trigger:type_name -> packets.DialogueTrigger
	2,  // 13: packets.ErrorResponse.code:type_name -> packets.ErrorCode
	0,  // 14: packets.AuthenticationRequest.type:type_name -> packets.AuthenticationType
	9,  // 15: packets.AuthenticationResponse.user_data:type_name -> packets.UserData
	15, // 16: packets.AuthenticationResponse.dialogue_trigger:type_name -> packets.DialogueTrigger
	11, // 17: packets.AccessibleChapterResponse.chapters:type_name -> packets.ChapterData
	14, // 18: packets.AccessibleEpisodesResponse.episodes:type_name -> packets.EpisodeData
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*FromClientToServer_AuthenticationRequest)(nil),
		(*FromClientToServer_EpisodesByChapterRequest)(nil),
		(*FromClientToServer_DigimonSelected)(nil),
		(*FromClientToServer_DialogueChoiceSelected)(nil),
		(*FromClientToServer_DialogueFinished)(nil),
		(*FromClientToServer_Dev)(nil),
	}
	file_packets_proto_msgTypes[1].OneofWrappers = []any{
		(*FromServerToClient_WebsocketId)(nil),
		(*FromServerToClient_ErrorResponse)(nil),
		(*FromServerToClient_AuthenticationResponse)(nil),
		(*FromServerToClient_ChapterDataResponse)(nil),
		(*FromServerToClient_EpisodeDataResponse)(nil),
		(*FromServerToClient_DialogueTrigger)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
