// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: server.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNKOWN_ERROR ErrorCode = 0
	// Authentication
	ErrorCode_INVALID_CREDENTIALS        ErrorCode = 1
	ErrorCode_USERNAME_TAKEN             ErrorCode = 2
	ErrorCode_USERNAME_TOO_SHORT_OR_LONG ErrorCode = 3
	ErrorCode_PASSWORD_TOO_SHORT         ErrorCode = 4 //USER_NOT_FOUND = 4;
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNKOWN_ERROR",
		1: "INVALID_CREDENTIALS",
		2: "USERNAME_TAKEN",
		3: "USERNAME_TOO_SHORT_OR_LONG",
		4: "PASSWORD_TOO_SHORT",
	}
	ErrorCode_value = map[string]int32{
		"UNKOWN_ERROR":               0,
		"INVALID_CREDENTIALS":        1,
		"USERNAME_TAKEN":             2,
		"USERNAME_TOO_SHORT_OR_LONG": 3,
		"PASSWORD_TOO_SHORT":         4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_server_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_server_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

type FromServerToClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*FromServerToClient_WebsocketId
	//	*FromServerToClient_ErrorResponse
	//	*FromServerToClient_AuthenticationResponse
	//	*FromServerToClient_ChapterDataResponse
	//	*FromServerToClient_EpisodeDataResponse
	//	*FromServerToClient_DialogueTrigger
	//	*FromServerToClient_DigimonTeamViewResponse
	Payload       isFromServerToClient_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromServerToClient) Reset() {
	*x = FromServerToClient{}
	mi := &file_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromServerToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromServerToClient) ProtoMessage() {}

func (x *FromServerToClient) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromServerToClient.ProtoReflect.Descriptor instead.
func (*FromServerToClient) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{0}
}

func (x *FromServerToClient) GetPayload() isFromServerToClient_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *FromServerToClient) GetWebsocketId() *WebsocketIDResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_WebsocketId); ok {
			return x.WebsocketId
		}
	}
	return nil
}

func (x *FromServerToClient) GetErrorResponse() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_ErrorResponse); ok {
			return x.ErrorResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetAuthenticationResponse() *AuthenticationResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_AuthenticationResponse); ok {
			return x.AuthenticationResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetChapterDataResponse() *AccessibleChapterResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_ChapterDataResponse); ok {
			return x.ChapterDataResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetEpisodeDataResponse() *AccessibleEpisodesResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_EpisodeDataResponse); ok {
			return x.EpisodeDataResponse
		}
	}
	return nil
}

func (x *FromServerToClient) GetDialogueTrigger() *DialogueTrigger {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_DialogueTrigger); ok {
			return x.DialogueTrigger
		}
	}
	return nil
}

func (x *FromServerToClient) GetDigimonTeamViewResponse() *DigimonTeamViewResponse {
	if x != nil {
		if x, ok := x.Payload.(*FromServerToClient_DigimonTeamViewResponse); ok {
			return x.DigimonTeamViewResponse
		}
	}
	return nil
}

type isFromServerToClient_Payload interface {
	isFromServerToClient_Payload()
}

type FromServerToClient_WebsocketId struct {
	WebsocketId *WebsocketIDResponse `protobuf:"bytes,1,opt,name=websocket_id,json=websocketId,proto3,oneof"`
}

type FromServerToClient_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

type FromServerToClient_AuthenticationResponse struct {
	AuthenticationResponse *AuthenticationResponse `protobuf:"bytes,3,opt,name=authentication_response,json=authenticationResponse,proto3,oneof"`
}

type FromServerToClient_ChapterDataResponse struct {
	ChapterDataResponse *AccessibleChapterResponse `protobuf:"bytes,4,opt,name=chapter_data_response,json=chapterDataResponse,proto3,oneof"`
}

type FromServerToClient_EpisodeDataResponse struct {
	EpisodeDataResponse *AccessibleEpisodesResponse `protobuf:"bytes,5,opt,name=episode_data_response,json=episodeDataResponse,proto3,oneof"`
}

type FromServerToClient_DialogueTrigger struct {
	DialogueTrigger *DialogueTrigger `protobuf:"bytes,6,opt,name=dialogue_trigger,json=dialogueTrigger,proto3,oneof"`
}

type FromServerToClient_DigimonTeamViewResponse struct {
	DigimonTeamViewResponse *DigimonTeamViewResponse `protobuf:"bytes,7,opt,name=digimon_team_view_response,json=digimonTeamViewResponse,proto3,oneof"`
}

func (*FromServerToClient_WebsocketId) isFromServerToClient_Payload() {}

func (*FromServerToClient_ErrorResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_AuthenticationResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_ChapterDataResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_EpisodeDataResponse) isFromServerToClient_Payload() {}

func (*FromServerToClient_DialogueTrigger) isFromServerToClient_Payload() {}

func (*FromServerToClient_DigimonTeamViewResponse) isFromServerToClient_Payload() {}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=packets.ErrorCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNKOWN_ERROR
}

// Authentication
type WebsocketIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebsocketIDResponse) Reset() {
	*x = WebsocketIDResponse{}
	mi := &file_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebsocketIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebsocketIDResponse) ProtoMessage() {}

func (x *WebsocketIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebsocketIDResponse.ProtoReflect.Descriptor instead.
func (*WebsocketIDResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{2}
}

func (x *WebsocketIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuthenticationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UserData        *UserData              `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	DialogueTrigger *DialogueTrigger       `protobuf:"bytes,3,opt,name=dialogue_trigger,json=dialogueTrigger,proto3" json:"dialogue_trigger,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticationResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthenticationResponse) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *AuthenticationResponse) GetDialogueTrigger() *DialogueTrigger {
	if x != nil {
		return x.DialogueTrigger
	}
	return nil
}

// General Info
type UserData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Level          int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp            int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Bits           int64                  `protobuf:"varint,4,opt,name=bits,proto3" json:"bits,omitempty"`
	Yen            int64                  `protobuf:"varint,5,opt,name=yen,proto3" json:"yen,omitempty"`
	StaminaCurrent int32                  `protobuf:"varint,6,opt,name=stamina_current,json=staminaCurrent,proto3" json:"stamina_current,omitempty"`
	StaminaMax     int32                  `protobuf:"varint,7,opt,name=stamina_max,json=staminaMax,proto3" json:"stamina_max,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{4}
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *UserData) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *UserData) GetYen() int64 {
	if x != nil {
		return x.Yen
	}
	return 0
}

func (x *UserData) GetStaminaCurrent() int32 {
	if x != nil {
		return x.StaminaCurrent
	}
	return 0
}

func (x *UserData) GetStaminaMax() int32 {
	if x != nil {
		return x.StaminaMax
	}
	return 0
}

// Stages
type AccessibleChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*ChapterData         `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessibleChapterResponse) Reset() {
	*x = AccessibleChapterResponse{}
	mi := &file_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessibleChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessibleChapterResponse) ProtoMessage() {}

func (x *AccessibleChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessibleChapterResponse.ProtoReflect.Descriptor instead.
func (*AccessibleChapterResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{5}
}

func (x *AccessibleChapterResponse) GetChapters() []*ChapterData {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type ChapterData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChapterId          int32                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	ChapterNumber      int32                  `protobuf:"varint,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	ChapterName        string                 `protobuf:"bytes,3,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	ChapterDescription string                 `protobuf:"bytes,4,opt,name=chapter_description,json=chapterDescription,proto3" json:"chapter_description,omitempty"`
	IsUnlocked         bool                   `protobuf:"varint,5,opt,name=is_unlocked,json=isUnlocked,proto3" json:"is_unlocked,omitempty"`
	IsBeaten           bool                   `protobuf:"varint,6,opt,name=is_beaten,json=isBeaten,proto3" json:"is_beaten,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChapterData) Reset() {
	*x = ChapterData{}
	mi := &file_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterData) ProtoMessage() {}

func (x *ChapterData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterData.ProtoReflect.Descriptor instead.
func (*ChapterData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{6}
}

func (x *ChapterData) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ChapterData) GetChapterNumber() int32 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *ChapterData) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *ChapterData) GetChapterDescription() string {
	if x != nil {
		return x.ChapterDescription
	}
	return ""
}

func (x *ChapterData) GetIsUnlocked() bool {
	if x != nil {
		return x.IsUnlocked
	}
	return false
}

func (x *ChapterData) GetIsBeaten() bool {
	if x != nil {
		return x.IsBeaten
	}
	return false
}

type AccessibleEpisodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episodes      []*EpisodeData         `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessibleEpisodesResponse) Reset() {
	*x = AccessibleEpisodesResponse{}
	mi := &file_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessibleEpisodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessibleEpisodesResponse) ProtoMessage() {}

func (x *AccessibleEpisodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessibleEpisodesResponse.ProtoReflect.Descriptor instead.
func (*AccessibleEpisodesResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{7}
}

func (x *AccessibleEpisodesResponse) GetEpisodes() []*EpisodeData {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type EpisodeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     int32                  `protobuf:"varint,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	EpisodeNumber int32                  `protobuf:"varint,2,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	EpisodeName   string                 `protobuf:"bytes,3,opt,name=episode_name,json=episodeName,proto3" json:"episode_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeData) Reset() {
	*x = EpisodeData{}
	mi := &file_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeData) ProtoMessage() {}

func (x *EpisodeData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeData.ProtoReflect.Descriptor instead.
func (*EpisodeData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{8}
}

func (x *EpisodeData) GetEpisodeId() int32 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *EpisodeData) GetEpisodeNumber() int32 {
	if x != nil {
		return x.EpisodeNumber
	}
	return 0
}

func (x *EpisodeData) GetEpisodeName() string {
	if x != nil {
		return x.EpisodeName
	}
	return ""
}

type DialogueTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogueId    string                 `protobuf:"bytes,1,opt,name=dialogue_id,json=dialogueId,proto3" json:"dialogue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialogueTrigger) Reset() {
	*x = DialogueTrigger{}
	mi := &file_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialogueTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogueTrigger) ProtoMessage() {}

func (x *DialogueTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogueTrigger.ProtoReflect.Descriptor instead.
func (*DialogueTrigger) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{9}
}

func (x *DialogueTrigger) GetDialogueId() string {
	if x != nil {
		return x.DialogueId
	}
	return ""
}

// DIGIMON
type DigibankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digimons      []*DigibankDigimonData `protobuf:"bytes,1,rep,name=digimons,proto3" json:"digimons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigibankResponse) Reset() {
	*x = DigibankResponse{}
	mi := &file_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigibankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigibankResponse) ProtoMessage() {}

func (x *DigibankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigibankResponse.ProtoReflect.Descriptor instead.
func (*DigibankResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{10}
}

func (x *DigibankResponse) GetDigimons() []*DigibankDigimonData {
	if x != nil {
		return x.Digimons
	}
	return nil
}

type DigibankDigimonData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Species       string                 `protobuf:"bytes,1,opt,name=species,proto3" json:"species,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigibankDigimonData) Reset() {
	*x = DigibankDigimonData{}
	mi := &file_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigibankDigimonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigibankDigimonData) ProtoMessage() {}

func (x *DigibankDigimonData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigibankDigimonData.ProtoReflect.Descriptor instead.
func (*DigibankDigimonData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{11}
}

func (x *DigibankDigimonData) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *DigibankDigimonData) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type DigimonTeamViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digimon       *DigimonData           `protobuf:"bytes,1,opt,name=digimon,proto3" json:"digimon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonTeamViewResponse) Reset() {
	*x = DigimonTeamViewResponse{}
	mi := &file_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonTeamViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonTeamViewResponse) ProtoMessage() {}

func (x *DigimonTeamViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonTeamViewResponse.ProtoReflect.Descriptor instead.
func (*DigimonTeamViewResponse) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{12}
}

func (x *DigimonTeamViewResponse) GetDigimon() *DigimonData {
	if x != nil {
		return x.Digimon
	}
	return nil
}

type DigimonData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Species       string                 `protobuf:"bytes,1,opt,name=species,proto3" json:"species,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	CurrentHp     int32                  `protobuf:"varint,4,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	CurrentMp     int32                  `protobuf:"varint,5,opt,name=current_mp,json=currentMp,proto3" json:"current_mp,omitempty"`
	Health        int32                  `protobuf:"varint,6,opt,name=health,proto3" json:"health,omitempty"`
	Mana          int32                  `protobuf:"varint,7,opt,name=mana,proto3" json:"mana,omitempty"`
	Attack        int32                  `protobuf:"varint,8,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,9,opt,name=defense,proto3" json:"defense,omitempty"`
	Speed         int32                  `protobuf:"varint,10,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigimonData) Reset() {
	*x = DigimonData{}
	mi := &file_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigimonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigimonData) ProtoMessage() {}

func (x *DigimonData) ProtoReflect() protoreflect.Message {
	mi := &file_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigimonData.ProtoReflect.Descriptor instead.
func (*DigimonData) Descriptor() ([]byte, []int) {
	return file_server_proto_rawDescGZIP(), []int{13}
}

func (x *DigimonData) GetSpecies() string {
	if x != nil {
		return x.Species
	}
	return ""
}

func (x *DigimonData) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DigimonData) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *DigimonData) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *DigimonData) GetCurrentMp() int32 {
	if x != nil {
		return x.CurrentMp
	}
	return 0
}

func (x *DigimonData) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *DigimonData) GetMana() int32 {
	if x != nil {
		return x.Mana
	}
	return 0
}

func (x *DigimonData) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *DigimonData) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *DigimonData) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_server_proto protoreflect.FileDescriptor

const file_server_proto_rawDesc = "" +
	"\n" +
	"\fserver.proto\x12\apackets\"\xdc\x04\n" +
	"\x12FromServerToClient\x12A\n" +
	"\fwebsocket_id\x18\x01 \x01(\v2\x1c.packets.WebsocketIDResponseH\x00R\vwebsocketId\x12?\n" +
	"\x0eerror_response\x18\x02 \x01(\v2\x16.packets.ErrorResponseH\x00R\rerrorResponse\x12Z\n" +
	"\x17authentication_response\x18\x03 \x01(\v2\x1f.packets.AuthenticationResponseH\x00R\x16authenticationResponse\x12X\n" +
	"\x15chapter_data_response\x18\x04 \x01(\v2\".packets.AccessibleChapterResponseH\x00R\x13chapterDataResponse\x12Y\n" +
	"\x15episode_data_response\x18\x05 \x01(\v2#.packets.AccessibleEpisodesResponseH\x00R\x13episodeDataResponse\x12E\n" +
	"\x10dialogue_trigger\x18\x06 \x01(\v2\x18.packets.DialogueTriggerH\x00R\x0fdialogueTrigger\x12_\n" +
	"\x1adigimon_team_view_response\x18\a \x01(\v2 .packets.DigimonTeamViewResponseH\x00R\x17digimonTeamViewResponseB\t\n" +
	"\apayload\"7\n" +
	"\rErrorResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.packets.ErrorCodeR\x04code\"%\n" +
	"\x13WebsocketIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb0\x01\n" +
	"\x16AuthenticationResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12.\n" +
	"\tuser_data\x18\x02 \x01(\v2\x11.packets.UserDataR\buserData\x12C\n" +
	"\x10dialogue_trigger\x18\x03 \x01(\v2\x18.packets.DialogueTriggerR\x0fdialogueTrigger\"\xbe\x01\n" +
	"\bUserData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x12\n" +
	"\x04bits\x18\x04 \x01(\x03R\x04bits\x12\x10\n" +
	"\x03yen\x18\x05 \x01(\x03R\x03yen\x12'\n" +
	"\x0fstamina_current\x18\x06 \x01(\x05R\x0estaminaCurrent\x12\x1f\n" +
	"\vstamina_max\x18\a \x01(\x05R\n" +
	"staminaMax\"M\n" +
	"\x19AccessibleChapterResponse\x120\n" +
	"\bchapters\x18\x01 \x03(\v2\x14.packets.ChapterDataR\bchapters\"\xe5\x01\n" +
	"\vChapterData\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x05R\tchapterId\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\x05R\rchapterNumber\x12!\n" +
	"\fchapter_name\x18\x03 \x01(\tR\vchapterName\x12/\n" +
	"\x13chapter_description\x18\x04 \x01(\tR\x12chapterDescription\x12\x1f\n" +
	"\vis_unlocked\x18\x05 \x01(\bR\n" +
	"isUnlocked\x12\x1b\n" +
	"\tis_beaten\x18\x06 \x01(\bR\bisBeaten\"N\n" +
	"\x1aAccessibleEpisodesResponse\x120\n" +
	"\bepisodes\x18\x01 \x03(\v2\x14.packets.EpisodeDataR\bepisodes\"v\n" +
	"\vEpisodeData\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\x05R\tepisodeId\x12%\n" +
	"\x0eepisode_number\x18\x02 \x01(\x05R\repisodeNumber\x12!\n" +
	"\fepisode_name\x18\x03 \x01(\tR\vepisodeName\"2\n" +
	"\x0fDialogueTrigger\x12\x1f\n" +
	"\vdialogue_id\x18\x01 \x01(\tR\n" +
	"dialogueId\"L\n" +
	"\x10DigibankResponse\x128\n" +
	"\bdigimons\x18\x01 \x03(\v2\x1c.packets.DigibankDigimonDataR\bdigimons\"K\n" +
	"\x13DigibankDigimonData\x12\x18\n" +
	"\aspecies\x18\x01 \x01(\tR\aspecies\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"I\n" +
	"\x17DigimonTeamViewResponse\x12.\n" +
	"\adigimon\x18\x01 \x01(\v2\x14.packets.DigimonDataR\adigimon\"\x81\x02\n" +
	"\vDigimonData\x12\x18\n" +
	"\aspecies\x18\x01 \x01(\tR\aspecies\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x05R\x03exp\x12\x1d\n" +
	"\n" +
	"current_hp\x18\x04 \x01(\x05R\tcurrentHp\x12\x1d\n" +
	"\n" +
	"current_mp\x18\x05 \x01(\x05R\tcurrentMp\x12\x16\n" +
	"\x06health\x18\x06 \x01(\x05R\x06health\x12\x12\n" +
	"\x04mana\x18\a \x01(\x05R\x04mana\x12\x16\n" +
	"\x06attack\x18\b \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\t \x01(\x05R\adefense\x12\x14\n" +
	"\x05speed\x18\n" +
	" \x01(\x05R\x05speed*\x82\x01\n" +
	"\tErrorCode\x12\x10\n" +
	"\fUNKOWN_ERROR\x10\x00\x12\x17\n" +
	"\x13INVALID_CREDENTIALS\x10\x01\x12\x12\n" +
	"\x0eUSERNAME_TAKEN\x10\x02\x12\x1e\n" +
	"\x1aUSERNAME_TOO_SHORT_OR_LONG\x10\x03\x12\x16\n" +
	"\x12PASSWORD_TOO_SHORT\x10\x04B\rZ\vpkg/packetsb\x06proto3"

var (
	file_server_proto_rawDescOnce sync.Once
	file_server_proto_rawDescData []byte
)

func file_server_proto_rawDescGZIP() []byte {
	file_server_proto_rawDescOnce.Do(func() {
		file_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)))
	})
	return file_server_proto_rawDescData
}

var file_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_server_proto_goTypes = []any{
	(ErrorCode)(0),                     // 0: packets.ErrorCode
	(*FromServerToClient)(nil),         // 1: packets.FromServerToClient
	(*ErrorResponse)(nil),              // 2: packets.ErrorResponse
	(*WebsocketIDResponse)(nil),        // 3: packets.WebsocketIDResponse
	(*AuthenticationResponse)(nil),     // 4: packets.AuthenticationResponse
	(*UserData)(nil),                   // 5: packets.UserData
	(*AccessibleChapterResponse)(nil),  // 6: packets.AccessibleChapterResponse
	(*ChapterData)(nil),                // 7: packets.ChapterData
	(*AccessibleEpisodesResponse)(nil), // 8: packets.AccessibleEpisodesResponse
	(*EpisodeData)(nil),                // 9: packets.EpisodeData
	(*DialogueTrigger)(nil),            // 10: packets.DialogueTrigger
	(*DigibankResponse)(nil),           // 11: packets.DigibankResponse
	(*DigibankDigimonData)(nil),        // 12: packets.DigibankDigimonData
	(*DigimonTeamViewResponse)(nil),    // 13: packets.DigimonTeamViewResponse
	(*DigimonData)(nil),                // 14: packets.DigimonData
}
var file_server_proto_depIdxs = []int32{
	3,  // 0: packets.FromServerToClient.websocket_id:type_name -> packets.WebsocketIDResponse
	2,  // 1: packets.FromServerToClient.error_response:type_name -> packets.ErrorResponse
	4,  // 2: packets.FromServerToClient.authentication_response:type_name -> packets.AuthenticationResponse
	6,  // 3: packets.FromServerToClient.chapter_data_response:type_name -> packets.AccessibleChapterResponse
	8,  // 4: packets.FromServerToClient.episode_data_response:type_name -> packets.AccessibleEpisodesResponse
	10, // 5: packets.FromServerToClient.dialogue_trigger:type_name -> packets.DialogueTrigger
	13, // 6: packets.FromServerToClient.digimon_team_view_response:type_name -> packets.DigimonTeamViewResponse
	0,  // 7: packets.ErrorResponse.code:type_name -> packets.ErrorCode
	5,  // 8: packets.AuthenticationResponse.user_data:type_name -> packets.UserData
	10, // 9: packets.AuthenticationResponse.dialogue_trigger:type_name -> packets.DialogueTrigger
	7,  // 10: packets.AccessibleChapterResponse.chapters:type_name -> packets.ChapterData
	9,  // 11: packets.AccessibleEpisodesResponse.episodes:type_name -> packets.EpisodeData
	12, // 12: packets.DigibankResponse.digimons:type_name -> packets.DigibankDigimonData
	14, // 13: packets.DigimonTeamViewResponse.digimon:type_name -> packets.DigimonData
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_server_proto_init() }
func file_server_proto_init() {
	if File_server_proto != nil {
		return
	}
	file_server_proto_msgTypes[0].OneofWrappers = []any{
		(*FromServerToClient_WebsocketId)(nil),
		(*FromServerToClient_ErrorResponse)(nil),
		(*FromServerToClient_AuthenticationResponse)(nil),
		(*FromServerToClient_ChapterDataResponse)(nil),
		(*FromServerToClient_EpisodeDataResponse)(nil),
		(*FromServerToClient_DialogueTrigger)(nil),
		(*FromServerToClient_DigimonTeamViewResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_proto_rawDesc), len(file_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_proto_goTypes,
		DependencyIndexes: file_server_proto_depIdxs,
		EnumInfos:         file_server_proto_enumTypes,
		MessageInfos:      file_server_proto_msgTypes,
	}.Build()
	File_server_proto = out.File
	file_server_proto_goTypes = nil
	file_server_proto_depIdxs = nil
}
